### ISSUE TITLE
Unable to match UTF-8 characters with PCRE

### ISSUE THREAD

**Issue by jeromelebleu** [rrthomas/lrexlib#14]
Hi!

I don't succeed to match UTF-8 characters with a pattern which yet works in other languages like Python. I'm using the last release 2.7.2 on a Debian-based system with Lua 5.15.
I'm trying to match any alphabetic characters including accented ones for example. Here is the code that I run in a Lua interpreter:

```
> rex = require "rex_pcre"
> re = rex.new([[^[^\W\d_]+$]], rex.flags().UTF8)
> = re:match("à")
nil
```

I tried many other variations - like using the bytes as decimal instead of the character - but it never matches the pattern.

It's probably more a mistake or a lack of understanding of the Lua language from myself than a real issue in your library... But if you can help me to make it works I would be most grateful!

Thanks in advance!

**Comment by shmuz** [comment]
`rex.flags().UTF8` is not enough. There is another flag in PCRE, named `PCRE_UCP` (see PCRE documentation). Try the following:
```
local F = rex.flags()
re = rex.new([[^[^\W\d_]+$]], F.UTF8+F.UCP)
```

**Comment by jeromelebleu** [comment]
Thanks a lot for your quick answer, it works perfectly! :)
