### ISSUE TITLE
Installation with luarocks

### ISSUE THREAD

**Issue by alex-mashin** [rrthomas/lrexlib#17]
Under 64-bit Ubuntu 14.04, `sudo luarocks install lrexlib-pcre` fails with

    Error: Could not find expected file libpcre.a, or libpcre.so, or libpcre.so.* for PCRE -- you may have to  install PCRE in your system and/or pass PCRE_DIR or PCRE_LIBDIR to the luarocks command.  Example: luarocks install lrexlib-pcre PCRE_DIR=/usr/local

`sudo luarocks install lrexlib-pcre PCRE_LIBDIR=/lib/x86_64-linux-gnu` works.

**Comment by shmuz** [comment]
I'd not consider this an issue. Lrexlib-pcre has a dependency (libpcre) and that dependency can be at different locations on different systems.

**Comment by rrthomas** [comment]
This is not an lrexlib issue, it's a bug in Debian/Ubuntu's luarocks, which seems to have been fixed in the 2.0.12 (and hence 2.2.0) package, so I suggest you either install that (e.g. from vivid, or rebuild), or install from source.
