### ISSUE TITLE
liblua5.1-rex_pcre.a on 64-bit

### ISSUE THREAD

**Issue by alex-mashin** [rrthomas/lrexlib#18]
liblua5.1-rex_pcre.a wouldn't link on 64-bit Ubunu while building a .so library, whether installed by apt or luarocks.

Compiler says:
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/liblua5.1-rex-pcre.a(lpcre.o): relocation R_X86_64_32 against «.rodata.str1.1» can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/liblua5.1-rex-pcre.a: error adding symbols: Bad value

Tried changing luarocks configuration (as per http://stackoverflow.com/questions/9136229/luarocks-fpic-error) and even rebuilding the package from sources, to no avail.

**Comment by rrthomas** [comment]
This is not an lrexlib bug, it's a luarocks configuration bug. Sorry I don't have time to help with that; ask on the luarocks mailing list, or, as suggested in rrthomas/lrexlib#17, install a newer Ubuntu package.
