### ISSUE TITLE
luarocks install error

### ISSUE THREAD

**Issue by playerzhj** [rrthomas/lrexlib#24]
luarocks install --local lrexlib-PCRE

> src/pcre/lpcre.c: 在函数‘Lpcre_fullinfo’中:
> src/pcre/lpcre.c:372: 错误：‘PCRE_INFO_JIT’未声明(在此函数内第一次使用)
> src/pcre/lpcre.c:372: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
> src/pcre/lpcre.c:372: 错误：所在的函数内也只报告一次。)
> src/pcre/lpcre.c:373: 错误：‘PCRE_INFO_JITSIZE’未声明(在此函数内第一次使用)
> src/pcre/lpcre.c:380: 错误：‘PCRE_INFO_MAXLOOKBEHIND’未声明(在此函数内第一次使用)
> src/pcre/lpcre.c:381: 错误：‘PCRE_INFO_MINLENGTH’未声明(在此函数内第一次使用)

lua version is 5.1.5

**Comment by shmuz** [comment]
**playerzhj**, thanks for the report. This is fixed in the repository.

**Comment by playerzhj** [comment]
Thanks for your fast response. It works！
