### ISSUE TITLE
PCRE_UTF8 support?

### ISSUE THREAD

**Issue by PaulBernier** [rrthomas/lrexlib#25]
Does lrexlib supports 'u' compilation flag for PCRE to support UTF-8? http://php.net/manual/en/reference.pcre.pattern.modifiers.php
I think it is not, out of curiosity I'd like to know what problem you encountered with that?
Thanks.

**Comment by shmuz** [comment]
If you want to specify pattern compilation flags as a string then only letters specified in the manual are supported. 'u' is not listed. But one can always specify **any** flags as bitwise OR combination of their numeric values.

We didn't encounter any problem with flags. In fact, adding support for 'u' is trivial.

**Comment by PaulBernier** [comment]
Got it, it works. Thanks for the very fast reply.
