### ISSUE TITLE
Need to install in pure Lua environment

### ISSUE THREAD

**Issue by LoganDark** [rrthomas/lrexlib#28]
**No dependencies will be available. Only pure Lua.** (And a few modifications you shouldn't worry about)
###### This library is written in C, which worries me.

**Comment by shmuz** [comment]
The above requirements suggest that Lrexlib is not the right library for your project.

**Comment by LoganDark** [comment]
Can you suggest a pure Lua PCRE alternative?

**Comment by shmuz** [comment]
Not that I know of.

You can look at [LuLPeg](https://github.com/pygy/LuLPeg) or [LPegLJ](https://github.com/sacek/LPegLJ) but (1) they run under LuaJIT and (2) LPeg syntax is very different from PCRE's (but one can use "re" module to get similar syntax).

I'm closing this issue as this is off-topic now.
