### ISSUE TITLE
Lua 5.4

### ISSUE THREAD

**Issue by osch** [rrthomas/lrexlib#36]
Building for Lua 5.4 leads to error `undefined symbol: luaL_optint`.

This has been fixed in commit 6b517b141c16a9366a2b2e70b5493aebc43beb45.

Therefore I would appreciate a new release of lrexlib, or are there other things to be done before this could be released for Lua 5.4?

**Comment by shmuz** [comment]
It could be released for Lua 5.4 and there are no known issues specific to Lua 5.4.
But as there is no new or changed functionality in the library the new release is not justified (IMHO).

**Comment by osch** [comment]
But if there is no new release, installing for example from luarocks will lead to a broken package under Lua 5.4. IMHO this would justify a new release. Also Arch Linux has now Lua 5.4 as default Lua interpreter. Installing lrexlib 2.9.0 also leads to a broken lrexlib there. The simplest solution for this would be to release lrexlib 2.9.1 with the latest commit.

**Comment by shmuz** [comment]
OK, version 2.9.1 has just been released.
@rrthomas, since I never uploaded rocks/rockspecs, could you please do that?

**Comment by osch** [comment]
We also need a git tag "rel-2-9-1".

**Comment by rrthomas** [comment]
Sorry @shmuz, I didn't see the bit about rocks/rockspecs. I've added the tag, @osch.

**Comment by rrthomas** [comment]
I've now made the release. @shmuz, making a release is simple: just "make release". There's just a one-off setup task: install `woger` from https://github.com/rrthomas/woger, and make sure you're authorized to make releases on luarocks.org. Any help you need, just ask.

**Comment by shmuz** [comment]
> making a release is simple: just "make release"

Thanks, will try the next time.

**Comment by andrewstarks** [comment]
Might want to update the description to include 5.4

> a Lua 5.1–5.3 binding

**Comment by rrthomas** [comment]
Done, thanks @andrewstarks.
