### ISSUE TITLE
Compiler warning about redefining lua_objlen symbol on Lua > 5.1 with compatibility

### ISSUE THREAD

**Issue by johnthacker** [rrthomas/lrexlib#47]
If Lua 5.2, 5.3, or 5.4 is compiled with Lua 5.1 compatibility - the symbol in luaconf.h varies, LUA_COMPAT_ALL in [5.2](https://www.lua.org/source/5.2/luaconf.h.html),  LUA_COMPAT_5_1 in [5.3](https://www.lua.org/source/5.3/luaconf.h.html) or LUA_COMPAT_5_3 in [5.4](https://www.lua.org/source/5.4/luaconf.h.html) - then there is already a line in luaconf.h in all three versions:

`#define lua_objlen(L,i)         lua_rawlen(L, (i))`

If that is the case, then many compilers will issue warnings about redefining the macro, especially because the line in https://github.com/rrthomas/lrexlib/blob/master/src/common.h#L10 is not exactly the same.
Would it be possible to either check to see if the symbol is already defined and if so not define it, or to define it using the same line as in the upstream Lua source with compatibility, to avoid the compiler warning?

**Comment by shmuz** [comment]
Thanks for the report.
Does the latest commit fix this issue?

**Comment by johnthacker** [comment]
That fixes the warning, thanks!
